name: frontend_flutter
description: Simple Flutter app that talks to a Django REST API running locally
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.0
  file_picker: ^5.2.3
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
