name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Java (required by Android SDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Install Android SDK command-line tools and required packages
      - name: Setup Android SDK
        run: |
          set -eux
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          export ANDROID_SDK_ROOT=/opt/android-sdk
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo unzip -o commandlinetools.zip -d /opt/android-sdk/cmdline-tools
          sudo mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest || true
          yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV

      - name: Accept Android Licenses
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Flutter pub get (frontend)
        run: |
          cd frontend_flutter
          # Ensure Flutter project structure is valid for CI builds (creates missing Android/iOS wrappers if needed)
          flutter create . || true
          flutter pub get

      - name: Build release APK (frontend)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          cd frontend_flutter
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: frontend_flutter/build/app/outputs/flutter-apk/app-release.apk
